# Generated by Django 5.0.4 on 2024-04-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=500)),
                ('NumberOfCopies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.IntegerField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_manager.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_manager.member')),
            ],
        ),
    ]
